#!/bin/bash
set -e
if [ "$RXV_DEV_USER" = "" ]; then
	exec /bin/bash
fi
if [ "$#" -ge 1 ]; then
    HOME=$RXV_DEV_HOME exec /usr/bin/chpst -u :$RXV_DEV_UID:$RXV_DEV_GID /bin/bash -c "$*"
else
    HOME=$RXV_DEV_HOME exec /usr/bin/chpst -u ${RXV_DEV_USER}:${RXV_DEV_USER}:adm:sudo /bin/bash
fi
