#!/bin/bash
set -e
if [ "$MIRROR" != "" ]; then
    MIRROR_ARG="--build-arg MIRROR=$MIRROR"
fi

BUILD_BASE=ubuntu:26.04
RISCV_TOOLCHAIN_MIRROR=https://www.jamieiles.com
if [ $(uname -m) = "x86_64" ]; then
    RISCV_TOOLCHAIN_ARCHIVE=gcc-riscv-unknown-elf-x86_64.tar.gz
elif [ $(uname -m) = "aarch64" ]; then
    RISCV_TOOLCHAIN_ARCHIVE=gcc-riscv-unknown-elf-aarch64.tar.gz
fi
docker build --build-arg RISCV_TOOLCHAIN_MIRROR=$RISCV_TOOLCHAIN_MIRROR --build-arg RISCV_TOOLCHAIN_ARCHIVE=$RISCV_TOOLCHAIN_ARCHIVE --build-arg BUILD_BASE=$BUILD_BASE $MIRROR_ARG -t rxv-build docker/build/
docker build --build-arg UID=$(id -u) -t rxv-dev -f docker/dev/Dockerfile .
