#!/bin/bash
DOCKER_INTERACTIVE_FLAGS="-it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

# Quartus 16.1 needs /sys bind mounted to avoid a segfault in libudev when
# doing the flexlm licensing.
docker run -w /workspaces/rxv \
    --privileged \
    --rm \
    $DOCKER_INTERACTIVE_FLAGS \
    -v /sys:/sys:ro \
    -v /etc/machine-id:/etc/machine-id \
    -v /home:/home \
    -v $HERE/..:/workspaces/rxv \
    -e RXV_DEV_USER=devuser \
    -e RXV_DEV_HOME=$HOME \
    -e RXV_DEV_UID=$(id -u) \
    -e RXV_DEV_GID=$(id -g) \
    rxv-dev:latest $@
