#!/bin/bash
DOCKER_INTERACTIVE_FLAGS="-it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

TOOL=docker
TOOL_ARGS="--privileged -v $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY"
MOUNT_ARGS="\
    -v /sys:/sys:ro \
    -v /etc/machine-id:/etc/machine-id \
    -v /usr/share/themes:/usr/share/themes:ro \
    -v /usr/share/icons:/usr/share/icons:ro \
"
if [[ "$OSTYPE" =~ "darwin" ]]; then
    TOOL=container
    TOOL_ARGS="--cpus 10 --memory 20G"
    DOCKER_INTERACTIVE_FLAGS="-it"
    MOUNT_ARGS="-v $HOME:$HOME"
fi

# Quartus 16.1 needs /sys bind mounted to avoid a segfault in libudev when
# doing the flexlm licensing.
$TOOL run $TOOL_ARGS -w /workspaces/rxv \
    $TOOL_ARGS \
    --rm \
    $DOCKER_INTERACTIVE_FLAGS \
    $MOUNT_ARGS \
    -v $HERE/..:/workspaces/rxv \
    -e XDG_RUNTIME_DIR=/tmp \
    -e WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
    -e RXV_DEV_USER=devuser \
    -e RXV_DEV_HOME=$HOME \
    -e RXV_DEV_UID=$(id -u) \
    -e RXV_DEV_GID=$(id -g) \
    -e SHELL=$SHELL \
    rxv-dev:latest $@
