#!/bin/bash

# Copyright Jamie Iles, 2020

set -e
tar --exclude=scripts/archive \
    --exclude=.git* \
    --exclude=.exrc \
    --exclude=_build \
    --exclude=*.tar.xz \
    --exclude=*.pyc \
    --exclude=*.pyo \
    --exclude=__pycache__ \
    --exclude=.*.swp \
    --exclude=.*.swo \
    --transform="s|^rxv|rxv-$(date +%Y%m%d)|g" -C .. rxv -cJf ../rxv-$(date +%Y%m%d).tar.xz
mv ../rxv-$(date +%Y%m%d).tar.xz .
