#!/usr/bin/env python3
# Copyright 2026 Jamie Iles
# SPDX-License-Identifier: Apache-2.0
#
# Convert an 8 pixel wide PSF1/PSF2 console font to a C array of the glyphs
# for the given Unicode code points, e.g.
#
#   psf2c.py /usr/share/consolefonts/Uni2-Fixed16.psf.gz 0x20-0x7e 0x2588 0x2591
import gzip
import sys


def load(path):
    data = (gzip.open if path.endswith('.gz') else open)(path, 'rb').read()
    if data[:2] == b'\x36\x04':
        mode, height = data[2], data[3]
        count = 512 if mode & 1 else 256
        glyphs = [data[4 + i * height:4 + (i + 1) * height] for i in range(count)]
        table = data[4 + count * height:] if mode & 2 else b''
        umap = {}
        pos = 0
        for g in range(count) if table else []:
            while True:
                cp = int.from_bytes(table[pos:pos + 2], 'little')
                pos += 2
                if cp == 0xffff:
                    break
                if cp != 0xfffe:
                    umap.setdefault(cp, g)
        return height, glyphs, umap
    if data[:4] == b'\x72\xb5\x4a\x86':
        hdr = [int.from_bytes(data[i:i + 4], 'little') for i in range(4, 32, 4)]
        _, hsize, flags, count, size, height, width = hdr
        assert width <= 8
        glyphs = [data[hsize + i * size:hsize + (i + 1) * size] for i in range(count)]
        umap = {}
        if flags & 1:
            table = data[hsize + count * size:].split(b'\xff')
            for g, entry in enumerate(table[:count]):
                for ch in entry.split(b'\xfe')[0].decode('utf-8', 'ignore'):
                    umap.setdefault(ord(ch), g)
        return height, glyphs, umap
    raise ValueError('not a PSF font')


def main():
    path = sys.argv[1]
    cps = []
    for arg in sys.argv[2:]:
        if '-' in arg:
            lo, hi = (int(x, 0) for x in arg.split('-'))
            cps.extend(range(lo, hi + 1))
        else:
            cps.append(int(arg, 0))
    height, glyphs, umap = load(path)
    print('// Generated by scripts/psf2c.py from %s' % path.split('/')[-1])
    print('#include <stdint.h>\n')
    print('#define FONT_HEIGHT %d\n' % height)
    print('const uint32_t font_codepoints[] = {')
    print('    ' + ', '.join('0x%04x' % c for c in cps))
    print('};\n')
    print('const uint8_t font_glyphs[][%d] = {' % height)
    for c in cps:
        g = glyphs[umap.get(c, umap.get(ord('?')))]
        print('    {' + ', '.join('0x%02x' % b for b in g[:height]) + '}, // U+%04x' % c)
    print('};\n')
    print('const unsigned font_num_glyphs = %d;' % len(cps))


if __name__ == '__main__':
    main()
