#!/usr/bin/env python3
import os
import re
import subprocess
import sys

TEST_RE = {
    'software': r'.*rv32[msu][aim]-[pv]-[^\.]*$',
    'rtl': r'.*rv32[msu][aim]-[p]-[^\.]*$',
}

SKIP_TESTS = {
    'software': [],
    # rv32si-p-dirty uses sv32 VM
    'rtl': ['rv32si-p-dirty']
}

def run_tests(runner, sim, test_tree):
    failures = []
    for root, dirs, files in os.walk(test_tree):
        for f in files:
            if not re.match(TEST_RE[sim], f):
                continue
            if f in SKIP_TESTS[sim]:
                continue
            try:
                subprocess.check_call(
                    [runner, '--compliance', sim, os.path.join(root, f),
                     '--waves', os.path.join(root, f) + '.fst',
                     '--trace', os.path.join(root, f) + '.trace'])
            except subprocess.CalledProcessError:
                failures.append(f)

    if failures:
        print('TESTS FAILED:')
        print('\n'.join(failures))
        sys.exit(1)

def main():
    if len(sys.argv) != 4:
        print('usage: {0} sim runner tree'.format(
            sys.argv[0]), file=sys.stderr)
        sys.exit(2)
    run_tests(sys.argv[1], sys.argv[2], sys.argv[3])

if __name__ == '__main__':
    main()
