#!/bin/bash
sim=$1
src=$2
obj=$3
target_dir=$4

priv_tests="\
ebreak
ecall
misalign-sw-01
misalign-sh-01
misalign-lw-01
misalign-lhu-01
misalign-lh-01"

find "$obj" -name '*.log' -delete
find "$obj" -name '*.signature.output' -delete
for isa in I M Zifencei privilege; do
	if [ $isa = privilege ]; then
        for test in $priv_tests; do
		    make -C "$src" WORK="$obj" RISCV_SIMULATOR="$sim" TARGETDIR=$target_dir \
		        RISCV_TARGET="rxv-simulator" RISCV_DEVICE=$isa -j1 simulate rv32i_sc_tests=$test
	        make -C "$src" WORK="$obj" RISCV_SIMULATOR="$sim" TARGETDIR=$target_dir \
		        RISCV_TARGET="rxv-simulator" RISCV_DEVICE=$isa -j1 verify rv32i_sc_tests=$test
        done
	else
	make -C "$src" WORK="$obj" RISCV_SIMULATOR="$sim" TARGETDIR=$target_dir \
		RISCV_TARGET="rxv-simulator" RISCV_DEVICE=$isa -j1 simulate
	make -C "$src" WORK="$obj" RISCV_SIMULATOR="$sim" TARGETDIR=$target_dir \
		RISCV_TARGET="rxv-simulator" RISCV_DEVICE=$isa -j1 verify
	fi
done
