#!/bin/bash
sim=$1
src=$2
obj=$3
target_dir=$4

find "$obj" -name '*.log' -delete
find "$obj" -name '*.signature.output' -delete
make -C "$src" WORK="$obj" RISCV_SIMULATOR="$sim" TARGETDIR=$target_dir \
	RISCV_TARGET="rxv-simulator" RISCV_DEVICE=I -j1 simulate
make -C "$src" WORK="$obj" RISCV_SIMULATOR="$sim" TARGETDIR=$target_dir \
	RISCV_TARGET="rxv-simulator" RISCV_DEVICE=I -j1 verify
