#!/bin/bash
set -e

NEXUS_USER=$1
NEXUS_PASSWORD=$2
NEXUS_PATH=$3

mkdir -p _build/ci || :
cd _build/ci

( cmake -GNinja /build && ninja -v | tee build.log ) || touch BUILD_FAIL
ctest -j$(nproc) -O ctest.log --output-on-failure && touch TEST_PASS || touch TEST_FAIL
tar czf tests.tar.gz --transform='s|^|tests/|g' $(find . \( -name '*.trace' -o -name '*.log' -o -name '*.fst' \))
git rev-parse HEAD > git_commit_id
curl -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file tests.tar.gz $NEXUS_PATH/tests.tar.gz
curl -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file git_commit_id $NEXUS_PATH/git_commit_id
curl -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file ctest.log $NEXUS_PATH/ctest.log
curl -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file build.log $NEXUS_PATH/build.log

for i in $(find . -maxdepth 1 \( -name "*PASS*" -o -name "*FAIL" \) ); do
    curl -u $NEXUS_USER:$NEXUS_PASSWORD --upload-file $i $NEXUS_PATH/$i
done
