#!/bin/bash
sim=$1
src=$2
obj=$3

find "$obj" -name '*.log' -delete
find "$obj" -name '*.signature.output' -delete
exec make -C "$src" O="$obj" RISCV_SIMULATOR="$sim" \
	RISCV_TARGET="rxv-simulator" RISCV_ISA=rv32i RISCV_DEVICE=rv32i -j1
