#!/usr/bin/env python3
import os
import re
import subprocess
import sys

TEST_RE = {
    'software': r'.*rv32[msu][aim]-[pv]-[^\.]*$',
    'rtl': r'.*rv32[msu][aim]-[pv]-[^\.]*$',
}

SKIP_TESTS = {
    # These are expected failures as they are testing hardware unaligned access
    # support which is not something that RXV implements.
    'software': ['rv32ui-v-ma_data', 'rv32ui-p-ma_data'],
    'rtl': ['rv32ui-v-ma_data', 'rv32ui-p-ma_data']
}

def run_tests(runner, sim, test_tree):
    failures = []
    for root, dirs, files in os.walk(test_tree):
        os.makedirs(os.path.join(root, sim), exist_ok=True)
        for f in files:
            if not re.match(TEST_RE[sim], f):
                continue
            if f in SKIP_TESTS[sim]:
                continue
            try:
                print(f'test: run {f}', file=sys.stderr)
                subprocess.check_call(
                    [runner, '--compliance', sim, os.path.join(root, f),
                     '--waves', os.path.join(root, sim, f) + '.fst',
                     '--trace', os.path.join(root, sim, f) + '.trace'])
            except subprocess.CalledProcessError:
                print(f'{f} failed', file=sys.stderr)
                failures.append(f)

    if failures:
        print('TESTS FAILED:', file=sys.stderr)
        print('\n'.join(failures), file=sys.stderr)
        sys.exit(1)

def main():
    if len(sys.argv) != 4:
        print('usage: {0} sim runner tree'.format(
            sys.argv[0]), file=sys.stderr)
        sys.exit(2)
    run_tests(sys.argv[1], sys.argv[2], sys.argv[3])

if __name__ == '__main__':
    main()
