#!/usr/bin/env python
import os
import re
import subprocess
import sys

TEST_RE = r'.*rv32[msu][aim]-[pv]-[^\.]*$'

def run_tests(runner, sim, test_tree):
    failures = []
    for root, dirs, files in os.walk(test_tree):
        for f in files:
            if not re.match(TEST_RE, f):
                continue
            try:
                subprocess.check_call(
                    [runner, '--compliance', sim, os.path.join(root, f), '--trace', os.path.join(root, f) + '.trace'])
            except subprocess.CalledProcessError:
                failures.append(f)

    if failures:
        print 'TESTS FAILED:'
        print '\n'.join(failures)
        sys.exit(1)

def main():
    if len(sys.argv) != 4:
        print >> sys.stderr, 'usage: {0} sim runner tree'.format(sys.argv[0])
        sys.exit(2)
    run_tests(sys.argv[1], sys.argv[2], sys.argv[3])

if __name__ == '__main__':
    main()
