namespace RXV.Trace;

enum Privilege : uint8 {
    U = 0,
    S = 1,
    M = 3
}

enum CSRId : uint16 {
    INVALID	    = 0x0000,
    SSTATUS     = 0x0100,
    SEDELEG     = 0x0102,
    SIDELEG     = 0x0103,
    SIE         = 0x0104,
    STVEC       = 0x0105,
    SCOUNTEREN  = 0x0106,
    SSCRATCH    = 0x0140,
    SEPC        = 0x0141,
    SCAUSE      = 0x0142,
    STVAL       = 0x0143,
    SIP         = 0x0144,
    SATP        = 0x0180,
    MSTATUS     = 0x0300,
    MISA        = 0x0301,
    MEDELEG     = 0x0302,
    MIDELEG     = 0x0303,
    MIE         = 0x0304,
    MTVEC       = 0x0305,
    MCOUNTEREN  = 0x0306,
    MSCRATCH    = 0x0340,
    MEPC        = 0x0341,
    MCAUSE      = 0x0342,
    MTVAL       = 0x0343,
    MIP         = 0x0344,
    PMPCFG0     = 0x03a0,
    PMPADDR0    = 0x03b0,
    PMPADDR1    = 0x03b1,
    PMPADDR2    = 0x03b2,
    PMPADDR3    = 0x03b3,
    TSELECT     = 0x07A0,
    TDATA1      = 0x07A1,
    TDATA2      = 0x07A2,
    TDATA3      = 0x07A3,
    STPVAL      = 0x05C0,
    STPERMS     = 0x05C1,
    MCYCLE      = 0x0B00,
    MINSTRET    = 0x0B02,
    MCYCLEH     = 0x0B80,
    MINSTRETH   = 0x0B82,
    UCYCLE      = 0x0C00,
    UTIME       = 0x0C01,
    UCYCLEH     = 0x0C80,
    UTIMEH      = 0x0C81,
    MVENDORID   = 0x0F11,
    MARCHID     = 0x0F12,
    MIMPID      = 0x0F13,
    MHARTID     = 0x0F14
}

table Register {
    id:uint8;
    read:bool;
    value:uint32;
}

table CSRValue {
    id:CSRId;
    value:uint32;
}

table MemAccess {
    addr:uint32;
    phys:uint32;
    value:uint32;
    size:uint8;
    read:bool;
}

table InstructionTrace {
    cycle_num:uint64;
    pc:uint32;
    pc_phys:uint32;
    instruction:uint32;
    gpr_accesses:[Register];
    mem_accesses:[MemAccess];
    csr_writes:[CSRValue];
    exception_raised:bool;
    privilege:Privilege;
}

table InterruptTrace {
    cycle_num:uint64;
    target_level:Privilege;
    csr_writes:[CSRValue];
}

union Event {
    InstructionTrace,
    InterruptTrace
}

table ProcessorTrace {
    events:[Event];
}

root_type ProcessorTrace;
