// Copyright 2026 Jamie Iles
// SPDX-License-Identifier: Apache-2.0
namespace RXV.Trace;

enum Privilege : uint8 {
    U = 0,
    S = 1,
    M = 3
}

enum CSRId : uint16 {
    INVALID	       = 0x0000,
    SSTATUS        = 0x0100,
    SEDELEG        = 0x0102,
    SIDELEG        = 0x0103,
    SIE            = 0x0104,
    STVEC          = 0x0105,
    SCOUNTEREN     = 0x0106,
    SENVCFG        = 0x010a,
    SSCRATCH       = 0x0140,
    SEPC           = 0x0141,
    SCAUSE         = 0x0142,
    STVAL          = 0x0143,
    SIP            = 0x0144,
    STIMECMP       = 0x014d,
    STIMECMPH      = 0x015d,
    SATP           = 0x0180,
    MSTATUS        = 0x0300,
    MISA           = 0x0301,
    MEDELEG        = 0x0302,
    MIDELEG        = 0x0303,
    MIE            = 0x0304,
    MTVEC          = 0x0305,
    MCOUNTEREN     = 0x0306,
    MSTATUSH       = 0x0310,
    MCOUNTINHIBIT  = 0x0320,
    MHPMEVENT3     = 0x0323,
    MHPMEVENT4     = 0x0324,
    MHPMEVENT5     = 0x0325,
    MHPMEVENT6     = 0x0326,
    MHPMEVENT7     = 0x0327,
    MHPMEVENT8     = 0x0328,
    MHPMEVENT9     = 0x0329,
    MHPMEVENT10    = 0x032a,
    MHPMEVENT11    = 0x032b,
    MHPMEVENT12    = 0x032c,
    MHPMEVENT13    = 0x032d,
    MHPMEVENT14    = 0x032e,
    MHPMEVENT15    = 0x032f,
    MHPMEVENT16    = 0x0330,
    MHPMEVENT17    = 0x0331,
    MHPMEVENT18    = 0x0332,
    MHPMEVENT19    = 0x0333,
    MHPMEVENT20    = 0x0334,
    MHPMEVENT21    = 0x0335,
    MHPMEVENT22    = 0x0336,
    MHPMEVENT23    = 0x0337,
    MHPMEVENT24    = 0x0338,
    MHPMEVENT25    = 0x0339,
    MHPMEVENT26    = 0x033a,
    MHPMEVENT27    = 0x033b,
    MHPMEVENT28    = 0x033c,
    MHPMEVENT29    = 0x033d,
    MHPMEVENT30    = 0x033e,
    MHPMEVENT31    = 0x033f,
    MSCRATCH       = 0x0340,
    MEPC           = 0x0341,
    MCAUSE         = 0x0342,
    MTVAL          = 0x0343,
    MIP            = 0x0344,
    PMPCFG0        = 0x03a0,
    PMPCFG1        = 0x03a1,
    PMPADDR0       = 0x03b0,
    PMPADDR1       = 0x03b1,
    PMPADDR2       = 0x03b2,
    PMPADDR3       = 0x03b3,
    PMPADDR4       = 0x03b4,
    PMPADDR5       = 0x03b5,
    PMPADDR6       = 0x03b6,
    PMPADDR7       = 0x03b7,
    MHPMEVENT3H    = 0x0723,
    MHPMEVENT4H    = 0x0724,
    MHPMEVENT5H    = 0x0725,
    MHPMEVENT6H    = 0x0726,
    MHPMEVENT7H    = 0x0727,
    MHPMEVENT8H    = 0x0728,
    MHPMEVENT9H    = 0x0729,
    MHPMEVENT10H   = 0x072a,
    MHPMEVENT11H   = 0x072b,
    MHPMEVENT12H   = 0x072c,
    MHPMEVENT13H   = 0x072d,
    MHPMEVENT14H   = 0x072e,
    MHPMEVENT15H   = 0x072f,
    MHPMEVENT16H   = 0x0730,
    MHPMEVENT17H   = 0x0731,
    MHPMEVENT18H   = 0x0732,
    MHPMEVENT19H   = 0x0733,
    MHPMEVENT20H   = 0x0734,
    MHPMEVENT21H   = 0x0735,
    MHPMEVENT22H   = 0x0736,
    MHPMEVENT23H   = 0x0737,
    MHPMEVENT24H   = 0x0738,
    MHPMEVENT25H   = 0x0739,
    MHPMEVENT26H   = 0x073a,
    MHPMEVENT27H   = 0x073b,
    MHPMEVENT28H   = 0x073c,
    MHPMEVENT29H   = 0x073d,
    MHPMEVENT30H   = 0x073e,
    MHPMEVENT31H   = 0x073f,
    TSELECT        = 0x07A0,
    TDATA1         = 0x07A1,
    TDATA2         = 0x07A2,
    TDATA3         = 0x07A3,
    STPVAL         = 0x05C0,
    STPERMS        = 0x05C1,
    MCYCLE         = 0x0B00,
    MINSTRET       = 0x0B02,
    MHPMCOUNTER3   = 0x0b03,
    MHPMCOUNTER4   = 0x0b04,
    MHPMCOUNTER5   = 0x0b05,
    MHPMCOUNTER6   = 0x0b06,
    MHPMCOUNTER7   = 0x0b07,
    MHPMCOUNTER8   = 0x0b08,
    MHPMCOUNTER9   = 0x0b09,
    MHPMCOUNTER10  = 0x0b0a,
    MHPMCOUNTER11  = 0x0b0b,
    MHPMCOUNTER12  = 0x0b0c,
    MHPMCOUNTER13  = 0x0b0d,
    MHPMCOUNTER14  = 0x0b0e,
    MHPMCOUNTER15  = 0x0b0f,
    MHPMCOUNTER16  = 0x0b10,
    MHPMCOUNTER17  = 0x0b11,
    MHPMCOUNTER18  = 0x0b12,
    MHPMCOUNTER19  = 0x0b13,
    MHPMCOUNTER20  = 0x0b14,
    MHPMCOUNTER21  = 0x0b15,
    MHPMCOUNTER22  = 0x0b16,
    MHPMCOUNTER23  = 0x0b17,
    MHPMCOUNTER24  = 0x0b18,
    MHPMCOUNTER25  = 0x0b19,
    MHPMCOUNTER26  = 0x0b1a,
    MHPMCOUNTER27  = 0x0b1b,
    MHPMCOUNTER28  = 0x0b1c,
    MHPMCOUNTER29  = 0x0b1d,
    MHPMCOUNTER30  = 0x0b1e,
    MHPMCOUNTER31  = 0x0b1f,
    MCYCLEH        = 0x0B80,
    MINSTRETH      = 0x0B82,
    MHPMCOUNTER3H  = 0x0b83,
    MHPMCOUNTER4H  = 0x0b84,
    MHPMCOUNTER5H  = 0x0b85,
    MHPMCOUNTER6H  = 0x0b86,
    MHPMCOUNTER7H  = 0x0b87,
    MHPMCOUNTER8H  = 0x0b88,
    MHPMCOUNTER9H  = 0x0b89,
    MHPMCOUNTER10H = 0x0b8a,
    MHPMCOUNTER11H = 0x0b8b,
    MHPMCOUNTER12H = 0x0b8c,
    MHPMCOUNTER13H = 0x0b8d,
    MHPMCOUNTER14H = 0x0b8e,
    MHPMCOUNTER15H = 0x0b8f,
    MHPMCOUNTER16H = 0x0b90,
    MHPMCOUNTER17H = 0x0b91,
    MHPMCOUNTER18H = 0x0b92,
    MHPMCOUNTER19H = 0x0b93,
    MHPMCOUNTER20H = 0x0b94,
    MHPMCOUNTER21H = 0x0b95,
    MHPMCOUNTER22H = 0x0b96,
    MHPMCOUNTER23H = 0x0b97,
    MHPMCOUNTER24H = 0x0b98,
    MHPMCOUNTER25H = 0x0b99,
    MHPMCOUNTER26H = 0x0b9a,
    MHPMCOUNTER27H = 0x0b9b,
    MHPMCOUNTER28H = 0x0b9c,
    MHPMCOUNTER29H = 0x0b9d,
    MHPMCOUNTER30H = 0x0b9e,
    MHPMCOUNTER31H = 0x0b9f,
    UCYCLE         = 0x0C00,
    UTIME          = 0x0C01,
    UCYCLEH        = 0x0C80,
    UTIMEH         = 0x0C81,
    SCOUNTOVF      = 0x0DA0,
    MVENDORID      = 0x0F11,
    MARCHID        = 0x0F12,
    MIMPID         = 0x0F13,
    MHARTID        = 0x0F14,
    MCONFIGPTR     = 0x0F15
}

table Register {
    id:uint8;
    read:bool;
    value:uint32;
}

table CSRValue {
    id:CSRId;
    value:uint32;
}

table MemAccess {
    addr:uint32;
    phys:uint32;
    value:uint32;
    size:uint8;
    read:bool;
}

table InstructionTrace {
    cycle_num:uint64;
    pc:uint32;
    pc_phys:uint32;
    instruction:uint32;
    gpr_accesses:[Register];
    mem_accesses:[MemAccess];
    csr_writes:[CSRValue];
    exception_raised:bool;
    privilege:Privilege;
}

table InterruptTrace {
    cycle_num:uint64;
    target_level:Privilege;
    csr_writes:[CSRValue];
}

union Event {
    InstructionTrace,
    InterruptTrace
}

table ProcessorTrace {
    events:[Event];
}

root_type ProcessorTrace;
