name: ci-build
on: [push]
jobs:
  build-test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: DOCKER_NONINTERACTIVE=1 ./docker/rxv-build -c "./scripts/run-ci \${{ secrets.NEXUS_USER }} \${{ secrets.NEXUS_PASSWORD }} \${{ secrets.NEXUS_HOST }}/repository/rxv-ci/ci/\${{ env.GITHUB_WORKFLOW }}/\$(date --iso-8601=seconds)"
